# Generated by Django 6.0.2 on 2026-03-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeverify',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='codeverify',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
