# Generated by Django 6.0.2 on 2026-03-17 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_codeverify_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeverify',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
